# Assignments

The course requires you to complete four types of "assignments" all of which are described on [the course assignments page](https://github.com/THOMASELOVE/500-2018/tree/master/assignments), and also listed as part of [the Class Schedule](https://github.com/THOMASELOVE/500-2018/blob/master/SCHEDULE.md).

The four types of assignments are:

1. A course project
2. An "observational studies in action" presentation
3. Seven brief "essays" about chapters in the Rosenbaum (2017) text, and
4. Five "homework" assignments involving using R to perform and present analyses.

## A course project

You will do a small observational study as a capstone project for the course. Your deliverables include:

1. a **proposal** which you will submit for my approval in February (you should expect the need to do a revision or two) and you will need to receive my approval by March 1.
2. an **update** verifying that you have the data and are proceeding appropriately, due April 1.
3. a final 20-minute **presentation** to the class about your results accompanied by an **abstract**, and by R Markdown and HTML files that describe the work you did. The presentations are on April 19 and 26. You will submit your abstract and presentation slides on April 18, and then submit all of the final materials by May 1.

Complete details on the Course Project [are available here](https://github.com/THOMASELOVE/500-2018/tree/master/projects).

## An "Observational Studies in Action" presentation

During the semester, you will be responsible for presenting the methods and results of an observational study from the literature that uses propensity scores. Your choice of manuscript must be accepted before March 1 by Dr. Love. After you've claimed a study, you'll give a 15-minute presentation of it to the class in late March / early April, and you'll also act as "second reviewer" for one of the studies selected by your colleagues.

Complete details on the OSIA work [are available here](https://github.com/THOMASELOVE/500-2018/tree/master/assignments/OSIA).

## Essays in reaction to the course text

In most sessions, we will be reading chapters from Paul Rosenbaum's *Observation and Experiment*. In early sessions, we will be reading several chapters at once (see [the Schedule](https://github.com/THOMASELOVE/500-2018/blob/master/SCHEDULE.md) for up-to-date details.) Beginning with Class 4, we will slow the pace to one chapter per class, and you will then produce an essay in reaction to each chapter (Chapters 7-13, specifically), to share with the rest of the class. 

The essay prompts [are available here](https://github.com/THOMASELOVE/500-2018/blob/master/assignments/essayprompts.md).

## Homework Assignments

The five "regular" homework assignments usually require you to do some analyses (using R and R Markdown) on data I will provide to you. All of these occur before the middle of March. 

Details on the homework assignments [are available here](https://github.com/THOMASELOVE/500-2018/tree/master/assignments).

## A Note on Feedback

500 is a very different course from 431-432 in terms of the "hands on" assistance that I make available to you as you're working on a homework assignment, in part because I don't have a TA for the course. In particular, I'm not going to review your code to be sure you're going in the right direction, even though I understand some of you have come to expect that from 431-432.

Instead, we discuss the HW assignments in class and I provide a detailed answer sketch after the fact. So if you have questions, please feel free to send them, and I'll answer sometimes, but what I am likely to say to anything I cannot resolve quickly for you (or think is worthy of deeper discussion as a group) is: 

1. That sounds like an excellent question to bring up on Thursday in class, and 
2. I'm going to let you (and everyone else) flounder a bit between now and our discussion of this HW in class.

## Grading

- If you complete all deliverables on time, and your project and OSIA presentations are solid, you will receive an A in the course.
    - If you mostly meet that standard but don't quite (either because more than one thing is late or because you have substantial project problems that linger), either an A or B is possible.
    - Grades that appear on Canvas will reflect successful and timely completion of assignments, and nothing more.
- This is an advanced graduate school course. I don't anticipate that anyone who makes a concerted effort will fall below the B standard, as no one has in the past. 
- If you have global or local concerns, raise them with me directly as soon as possible. Email is likely the best approach.

